### PR TITLE
Clarify usage of ``aenea/aenea.json``

### LINKED ISSUE #125: Socket error connecting to aenea server
First of all, thanks for this awesome project, I highly appreciate the work and the throrough documentation!

I basically completed all the steps of the short tutorial and the host-only adapter has been set up and can be pinged from the Guest as well as the Host (aenea.json and config.py have been adapted with the same IP accordingly). However, when I try to start DNS with, I get the following error:

_Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds._

It makes tracking down the point of failure quite hard since everything else seems to work fine.

Does anyone have an idea?

Thanks a lot in advance!

### PR DESCRIPTION
**Pull request by dylan-chong**
I've only actually changed the first two lines of the changes shown under 'files changed'.
the rest of the changes are just making sure the list numbers are correct

Fixes #125 by clarifying readme to avoid issue in the  first place

### CODE REVIEW

**Comment by dylan-chong** [comment]
@sparkvilla Do you think this will be clear enough for someone else reading the readme?

**Comment by sparkvilla** [comment]
I think so, especially the point 2a is much clearer now!

**Comment by dylan-chong** [comment]
@calmofthestorm Could you merge this pull request?

**Comment by calmofthestorm** [comment]
Thanks for the fix! I really appreciate you taking the time to follow up on user feedback on the instructions, it's crucial given what a complex setup this is.

**Pull request merged**
