### PR TITLE
Handle basic alt-key sequences for extended ASCII chars in the aenea client.

### PR DESCRIPTION
**Pull request by nirvdrum**
The basic problem I'm trying to fix here is Dragon 14 (maybe earlier too?) will send an en dash character when the 'dash' command is used in the middle of a dictation sequence. This character is `\x96` in extended ASCII. Tkinter sends the key press the way one would typically enter extended ASCII characters on Windows: by sending an Alt_L press followed by the numeric sequence (0, 1, 5, 0, in this case).

I've been unable to train myself to replace 'dash' with 'hyphen' thus far and what happens is the aenea client sends over a "0150" instead. It's been frustrating me, so I wanted to fix it.

The approach taken here is to look at both the char and keysym attributes of the event. The char will contain the en dash character as a Unicode code point at the end of the sequence, when the keysym would be '??'. To track through this, I implemented a small state machine that is activated when the 'Alt_L' keysym is encountered.

There is a hole in the state machine: if someone presses 'Alt_L' followed by the '0' key by typing in the aenea client, all characters will be discarded until the '??' keysym is encountered, marking the end of the sequence. It seems extremely unlikely this would ever happen in the real world and I don't think it can happen at all via dictation. Should it happen, simply pressing 'Alt_L' again would reset the state.

I'm sure there's more clean up that could be done here. Before investing too much more into it, I want to get buy-in first. I'm already finding it helpful.

### CODE REVIEW

**Comment by calmofthestorm** [comment]
OOOH THAT'S WHAT CAUSES THAT! Yeah this was irritating me as well. Thanks for taking a look and fixing it!

I agree this minor error isn't a problem, given there are few (if any) reasons to type directly in the client and even then it's a edge case.

Just to verify: Does this also mean that saying, eg, "Press alt s" will still work?

One minor nit: Would it be cleaner to move the state machine transition/action logic into AltKeySequenceState?

**Comment by nirvdrum** [comment]
I'm not sure on "press alt s". Using dragonfly-scripts, there's an explicit grammar option for this that uses Key() and ends up bypassing the Tkinter window entirely. I tried to removing that and things stopped working, but I don't see them ever work on master. It looks like things come in as two keypresses: 'Alt_L' followed by 's'. The version on master would just discard the 'Alt_L' and then type the 's'.

With the basic mechanism in place, we can support key combinations more easily. I guess I just never felt that pain because dragonfly-scripts circumvents the problem altogether.

**Comment by nirvdrum** [comment]
As for moving the state machine logic into `AltKeySequenceState`, that's certainly doable. I wrote the class as a poor man's enum because Python 2.7 doesn't have enum without requiring an external package. As such, it's very bare bones.

I don't care much one way or the other. I can move the state into there -- it'll just make the control flow a bit odder since there are fail-fast paths.

**Comment by calmofthestorm** [comment]
State machine: Good point on the control paths. I'm fine with whatever you think is best.

Alt-S: Mostly just curious. As you point out, there are grammars, and more importantly it's not like it worked before:P

**Comment by calmofthestorm** [comment]
Thanks!

**Pull request merged**
