### PR TITLE
Add Recognition Results plugin

### PR DESCRIPTION
**Pull request by facundoq**
This PR adds a Aenea plugin to display a recognition results window similar to that found in DNS ([original repository](https://github.com/facundoq/aenea_recognition_results)).

I believe this would be a neat feature to have by default. Right now, its hard to tell when a phrase has not been recognized when not simply dictating text that's being literally typed in the screen. Or for example, when a phrase was actually recognized correctly, but the focus was in another window. 

The only additional dependency this plugin adds is `tk` for python, which can be readily installed in most distros.
* Ubuntu and derivatives: `sudo apt install python-tk`
* Arch:  `sudo pacman -S tk`

Please note that the plugin uses a local file in the server to communicate the results to the recognition window. This file stores in plain text the results of your speech. If security or privacy of what you input is a concern, you should delete this file regularly and/or take the appropiate measures. By default, the file is `~/.aenea_phrases.log`. 

I haven't found a how to contribute guide, so if you're willing to merge this I'm expecting additional guidance into where to place docs.

### CODE REVIEW

**Comment by synkarius** [comment]
@LexiconCode This may be of interest to you.

**Comment by calmofthestorm** [comment]
Thanks, this is very nice, and also serves as a demo of how to write a plugin, as an added bonus! I think it's fine to just include the docs in the main README. I'm open to other suggestions though. If we ever have a ton of plugins I'd want to move them to a separate repository (as with grammars) and document them there, but this is 1) the first plugin anyone has submitted upstream here and 2) very useful functionality.

Thanks for making it a plugin by the way -- it makes me much less nervous about the potential to add dependencies, break things, etc.

Did you want to add docs to this PR or make a separate one? I'm ready to merge this but can wait for docs if you want to include them with the code.

**Comment by facundoq** [comment]
Great! I'll push a version with the docs in the main README.md so we merge all at once if that's ok, in case something comes up.

**Comment by facundoq** [comment]
I updated the main readme, please check the `Aenea Recognition Bar` section in [the new version](https://github.com/facundoq/aenea/blob/master/README.rst)!

**Comment by calmofthestorm** [comment]
Sorry for the delay, and thank you for the contribution!

**Comment by calmofthestorm** [comment]
It's not worth reverting over, but if you have a chance, could you fix the lint errors that are causing the CI to fail? It should be straightforward, and some like the unused variable make me concerned it may indicate a more serious bug.

2.91s$ PATH="${HOME}/.local/bin:${PATH}" python lint.py
537./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:10: 'Tkinter as tk' imported but unused
538./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:11: 'from Tkinter import *' used; unable to detect undefined names
539./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:12: 'os' imported but unused
540./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:25: 'Tk' may be undefined, or defined from star imports: Tkinter
541./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:29: 'Frame' may be undefined, or defined from star imports: Tkinter
542./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:32: 'StringVar' may be undefined, or defined from star imports: Tkinter
543./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:34: 'Label' may be undefined, or defined from star imports: Tkinter
544./server/linux_x11/plugins/recognitionbar/recognitionbar_tk.py:44: 'Button' may be undefined, or defined from star imports: Tkinter
545./client/_recognition_results_observer.py:20: local variable 'pid' is assigned to but never used
546./client/_recognition_results_observer.py:27: local variable 'pid' is assigned to but never used
547./client/_recognition_results_observer.py:34: local variable 'pid' is assigned to but never used
548The command "PATH="${HOME}/.local/bin:${PATH}" python lint.py" exited with 1.

**Comment by facundoq** [comment]
Sure, I was actually going to rebase to leave a single commit, just give me
a few days to test everything one more time.

**Pull request merged**
